---
title: "Bio"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


I'm a sociologist, data scientist, experimentalist, and builder. 

I obtained my PhD in 2020 from Cornell University, where I studied under Michael Macy. My academic interests include social contagion, homophily in networks, online conversations, and experimental design.

I currently work on experimentation and Bayesian stats in the political realm.

Lately, I write on my [substack blog](https://georgeberry.substack.com/) before publishing elsewhere, and I'm active on [twitter](https://twitter.com/george_berry).

Some publications you may find interesting

* [How to evaluate presidential election forecasts in less than 1000 years](https://osf.io/bjf6x)
* [Empirical work on friendship loss after the 2016 election and its relationship to fears of social breakdown](https://osf.io/preprints/socarxiv/cqrgp/)
* [Field experiments for studying online conversations](https://arxiv.org/pdf/1702.06677.pdf)
* [Fundamental problems for studying social influence in networks](https://arxiv.org/pdf/1702.02700.pdf)

I have also written a (hopefully) clear [introduction to causal inference](https://osf.io/preprints/socarxiv/ncvqs/) for folks studying web data.

## Socials

* [google scholar](https://scholar.google.com/citations?user=QqsOZm4AAAAJ&hl=en)

* [twitter](https://twitter.com/george_berry)

* [github](https://github.com/georgeberry)

* [substack blog](https://georgeberry.substack.com/)

* george.e.berry at gmail dot com

## Work

I currently work as a Machine Learning Engineer at Blue Rose Research, where I focus on modeling and measurement.

## Side hustles

If you'd like my advice or input on something, reach out via email and we can discuss. I get these requests a **lot** and I do charge for them, just so you know.

I co-own a small trading card store called **Card Shop Near Me** in central NJ (near Princeton). Come visit us if you're in the area! Check out our [Shopify store](https://cardshopnearmenj.com/), [Google Maps profile](https://maps.app.goo.gl/8u5fBXc65TtUmu368), [eBay shop](https://www.ebay.com/str/pinklabelcards), and follow us on [Instagram](https://www.instagram.com/cardshopnearme/).
